spring:
  datasource:
    url: jdbc:mysql://localhost:3307/vollmed_api_test?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    inittialization-mode: always

jpa:
  dataBase-platform: org.hibernate.dialect.MySQL8Dialect
  hibernate:
    ddl-auto: update