create table pacientes (

    id bigint not null auto_increment primary key,
    guia varchar(14) not null,
    registro varchar(30) not null unique,
    categoria varchar(2) not null,
    data_cadastro varchar(10) not null,
    data_habilitacao varchar(10) not null,
    nome varchar(100) not null,
    data_nascimento varchar(10) not null,
    sexo varchar(10) not null,
    cpf varchar(14) not null unique,
    nacionalidade varchar(100) not null,
    nome_mae varchar(100) not null,
    nome_pai varchar(100) not null,
    telefone varchar(20) not null,
    logradouro varchar(100) not null,
    bairro varchar(100) not null,
    cep varchar(9) not null,
    numero varchar(20),
    complemento varchar(100),
    cidade varchar(100) not null,
    uf char(2) not null,
    ativo tinyint default 1 not null
);