create table pacientes (

    id bigint not null auto_increment primary key,
    guia int not null,
    registro varchar(30) not null unique,
    categoria varchar(2) not null,
    solicitacao varchar(50) not null,
    data_cadastro varchar(10) not null,
    data_habilitacao varchar(10) not null,
    nome varchar(100) not null,
    data_nascimento varchar(10) not null,
    sexo varchar(10) not null,
    identidade varchar(45) not null,
    orgao varchar(10) not null,
    uf_identidade varchar(2) not null,
    naturalidade varchar(45) not null,
    uf_naturalidade varchar(45) not null,
    nacionalidade varchar(45) not null,
    nome_mae varchar(100) not null,
    nome_pai varchar(100) not null,
    logradouro varchar(100) not null,
    numero varchar(10) not null,
    bairro varchar(45) not null,
    cidade varchar(100) not null,
    uf_cidade varchar(2) not null,
    cep varchar(9) not null,
    complemento varchar(45),
    cpf varchar(14) not null unique,
    telefone varchar(20) not null,
    status tinyint not null
);